version: "3.3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 4
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  registry:
    image: frolvlad/alpine-oraclejdk8:slim
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - ./target/registry.jar:/registry.jar
      - /data:/data
      - ./logs:/logs
    command: java -jar -Xms1024m -Xmx2048m -XX:+UseG1GC -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=50M -Xloggc:logs/sunbirdrc_gc.log /registry.jar
    environment:
      - sunbird_sso_publickey=${sunbird_sso_publickey}
      - sunbird_sso_realm=${sunbird_sso_realm}
      - sunbird_sso_url=${sunbird_sso_url}
      - sunbird_sso_username=${sunbird_sso_username}
      - sunbird_sso_password=${sunbird_sso_password}
      - sunbird_sso_client_id=${sunbird_sso_client_id}


