swagger: '2.0'
info:
  version: '1.0.0'
  title: Notification service
  description: Notification service

securityDefinitions:
  hasRole:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://sunbirdrc.dev/keycloak/auth/realms/sunbirdrc/protocol/openid-connect/auth'
    tokenUrl: 'https://sunbirdrc.dev/keycloak/auth/realms/sunbirdrc/protocol/openid-connect/token'
    scopes:
      admin: scope of super admin
      facility-admin: scope of facility admin
      facility-staff: scope of facility staff

security: []
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    get:
      tags:
        - health
      summary: Get the health status
      description: API to get the notification health status
      responses:
        200:
          description: OK
          schema:
            type: object
  /notification:
    get:
      tags:
        - notification
      summary: Get the last notifications sent
      description: Temporary API to get the last notifications sent
      responses:
        200:
          description: OK
          schema:
            type: object
    post:
      tags:
        - notification
      summary: Notify the intended person using different channels
      description: Common notification service for different channels like eSMS, email etc. Target address can depict specifics about mode and channel
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/NotificationRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Success'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
  Success:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
  NotificationRequest:
    type: object
    required:
      - recipient
      - message
    properties:
      recipient:
        type: string
        description: this can use address like tel:234343434 or mailto:user@example.com
      message:
        type: string
      subject:
        type: string
      #attachment:
      #  type:

host: sunbirdrc.dev
basePath: /notification-service/v1
schemes:
  - https