clickhouse:
  dsn: localhost:9002
  database: default
kafka:
  bootstrapServers: localhost:9094
  metricsTopic: metrics
database:
  providerName: clickhouse
redis:
  url: localhost:6379
cron:
  scheduleTime: 00:00
  scheduleInterval: 7
  enable: true